### ISSUE TITLE
Unable to setup via generator

### ISSUE THREAD

**Issue by nessthehero** [romainberger/yeoman-wordpress#25]
Did a fresh install of generator-yo-wordpress via

```
npm install -g generator-yo-wordpress
```

Walked through initial steps but after typing in Author URI, I am met with this error:

```
$ yo yo-wordpress


Trying to get the latest stable version of Wordpress
Latest version: 3.5.2
Name of the theme you want to use (mytheme)
Starter theme (please provide a github link) (https://github.com/automattic/_s)

Which version of Wordpress do you want? (3.5.2)
Would you like to include RequireJS (for AMD support)? Y
Author name Ian
Author URI http://www.nessthehero.com

c:\Users\Ian Moffitt\AppData\Roaming\npm\node_modules\generator-yo-    wordpress\app
\index.js:121
    self.themeNameOriginal = props.themeName
                                  ^
TypeError: Cannot read property 'themeName' of null
    at c:\Users\Ian Moffitt\AppData\Roaming\npm\node_modules\generator-yo-wordpress\app\index.js:121:35
    at next (c:\Users\Ian Moffitt\AppData\Roaming\npm\node_modules\generator-yo-wordpress\node_modules\yeoman-generator\lib\actions\prompt.js:21:14)
    at c:\Users\Ian Moffitt\AppData\Roaming\npm\node_modules\generator-yo-wordpress\node_modules\yeoman-generator\lib\actions\prompt.js:33:7
    at Interface.onLine (c:\Users\Ian Moffitt\AppData\Roaming\npm\node_modules\generator-yo-wordpress\node_modules\yeoman-generator\node_modules\read\lib\read.js:110:5)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
```

**Comment by romainberger** [comment]
I forgot to update the version of a dependency... stupid mistake sorry about that (and thanks for letting me know).
I'm trying to publish to npm but the registry seems to be down. I'll do it as soon as I can.

**Comment by romainberger** [comment]
I've pushed the patch, an update should fix everything

**Comment by nessthehero** [comment]
Yup, all fixed. Thanks.
