### ISSUE TITLE
Is this related to Issue #31 ?

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [romainberger/yeoman-wordpress#34]
Trying to get the latest stable version of Wordpress

/usr/local/lib/node_modules/generator-yo-wordpress/app/index.js:67
        if (semverVersionString.match(patternShort)) semverVersionString += '.
                                ^
TypeError: Cannot call method 'match' of undefined
    at /usr/local/lib/node_modules/generator-yo-wordpress/app/index.js:67:33
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:451:12)

**Comment by romainberger** [comment]
That's weird, I just made a clean install and it's not happening. Was it the first time you installed the package or was it an update?

It's definitely related to #31 as this code was introduced with these PR.

**Comment by Gong-Bao-Chicken** [comment]
just installed the generator through yo install generator..  :(

also updated all generators and they are all up to date...

**Comment by rspereira** [comment]
Had problem here too

Trying to get the latest stable version of Wordpress

/usr/local/lib/node_modules/generator-yo-wordpress/app/index.js:56
        self.writeln('exec error: ' + err)
             ^
TypeError: Object #<Generator> has no method 'writeln'
    at /usr/local/lib/node_modules/generator-yo-wordpress/app/index.js:56:14
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

Installed through yo install generator too, its first time installing the package and thay are all up to date.

**Comment by ekancepts** [comment]
**My system config and yeoman config details**

_My OS ubuntu 12.04_

```
$ yo -v
1.1.2
$ npm -v
1.3.21
$ node -v
v0.10.24
```

I created new wordpress app with this generator without any errors. I think this issue can be closed if no further inputs about this issue.
