### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by dabernathy89** [romainberger/yeoman-wordpress#35]
Just tried installing from the README directions, and i'm running into this error:

npm 1.3.8
yo 1.0.3

```
Daniels-MacBook-Air:vagrant danielabernathy$ yo yo-wordpress

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/lib/util/common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/lib/base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Daniels-MacBook-Air:vagrant danielabernathy$
```

**Comment by amitburst** [comment]
Also having this issue

**Comment by amitburst** [comment]
Still having this issue. Tried reinstalling, npm cache clean, etc. Perhaps the dependency versions need to be updated again? I think there are newer versions of both yeoman-generator and yo.

**Comment by romainberger** [comment]
Sorry for the delay I was on vacation with no laptop.

I've change the dependencies to force the latest version. The error comes from the yeoman-generator package where it uses the chalk package. 

Can you please tell me if you still have the error (it always work for me :angry: ) ?

**Comment by amitburst** [comment]
Seems to be working now! Thanks. :)

**Comment by romainberger** [comment]
Great!
