### ISSUE TITLE
YeomanConfig is not defined

### ISSUE THREAD

**Issue by wmena** [romainberger/yeoman-wordpress#38]
Hello Romain,

I'm having this issue when I run the generator: 
is this from the generator?

undefined:9
((__t = ( yeomanConfig.themeName )) == null ? '' : __t) +
          ^
ReferenceError: yeomanConfig is not defined
    at eval (/lodash/template/source[0]:9:11)
    at Generator.underscore [as _engine](/usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/lib/util/engines.js:33:30)
    at Generator.engine (/usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/lib/actions/actions.js:291:10)
    at Generator.template (/usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/lib/actions/actions.js:269:15)
    at Generator.createYeomanFiles (/usr/local/share/npm/lib/node_modules/generator-yo-wordpress/app/index.js:274:8)
    at /usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/lib/base.js:290:20
    at /usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/node_modules/async/lib/async.js:548:21
    at /usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/node_modules/async/lib/async.js:224:13
    at iterate (/usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/node_modules/async/lib/async.js:131:13)
    at /usr/local/share/npm/lib/node_modules/generator-yo-wordpress/node_modules/yeoman-generator/node_modules/async/lib/async.js:142:25

Cheers,
Will

**Comment by romainberger** [comment]
Awwwww I don't even know how I missed this. Sorry
